# Your project's server will run on localhost:xxxx at this port
PORT: 8000

# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 9"
  - "ios >= 7"

# UnCSS will use these settings
UNCSS_OPTIONS:
  html:
    - "src/**/*.html"
  ignore:
    - !!js/regexp .foundation-mq
    - !!js/regexp ^\.is-.*

# Gulp will reference these paths when it copies files
PATHS:
  # SRC
  src: "src"
  srcPages: "src/pages/**/*.{html,hbs,handlebars}"
  srcScssApp: "src/assets/scss/app.scss"
  srcFilesScss: "src/assets/scss/**/*.scss"
  srcFilesImages: "src/assets/img/**/*.{gif,jpeg,jpg,png,tiff,webp}"
  srcFilesJS: "src/assets/js/lib/**/*.js"
  srcSVG: "src/assets/svg"
  srcFilesSVG:
    - "src/assets/svg/**/*.svg"
    - "!src/assets/svg/templates/svg-symbols.{css,svg}"
    - "!src/assets/svg/svg-symbols.{css,svg}"
  srcSvgSpriteInjectionInput: "src/partials/svg/svg-sprite-inject.html"
  srcSvgSpriteInjectionOutput: "src/partials/svg"

  # DIST
  dist: "dist"
  distAssets: "dist/assets"
  distCSS: "dist/assets/css"
  distJS: "dist/assets/js"
  distImages: "dist/assets/img"

  # STYLEGUIDE
  srcStyleguideFiles: "src/styleguide/**/*.{html,md}"

  # Paths to static assets that aren't images, CSS, or JavaScript
  assets:
    - "src/assets/**/*"
    - "!src/assets/{img,js,scss}{,/**/*}"
  # Paths to Sass libraries, which can then be loaded with @import
  sassLibraries:
    - "node_modules/foundation-sites/scss"
    - "node_modules/motion-ui/src"
  # Paths to JavaScript entry points for webpack to bundle modules
  entries:
    - "src/assets/js/app.js"
